# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.3.0"
wally = "UpliftGames/wally@0.3.2"
lune = "filiptibell/lune@0.7.2"
darklua = "seaofvoices/darklua@0.9.0"
# rojo = "rojo-rbx/rojo@6.2.0"